<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="15" failed="0" total="15" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="26" started-at="2016-01-22T13:31:54Z" finished-at="2016-01-22T13:31:54Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="26" started-at="2016-01-22T13:31:54Z" finished-at="2016-01-22T13:31:54Z">
      <class name="backend.MakeUserTest">
        <test-method status="SKIP" signature="openUserPage()[pri:0, instance:backend.MakeUserTest@bfbefc]" name="openUserPage" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="open user panel" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openUserPage -->
        <test-method status="SKIP" signature="makeUser()[pri:0, instance:backend.MakeUserTest@bfbefc]" name="makeUser" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="create user" depends-on-methods="backend.MakeUserTest.openUserPage" finished-at="2016-01-22T14:31:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MakeUserTest.makeUser()[pri:0, instance:backend.MakeUserTest@bfbefc] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MakeUserTest.makeUser()[pri:0, instance:backend.MakeUserTest@bfbefc] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:160)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:100)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeUser -->
        <test-method status="SKIP" signature="validateNewUser()[pri:0, instance:backend.MakeUserTest@bfbefc]" name="validateNewUser" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="check if new user was succesfully added" depends-on-methods="backend.MakeUserTest.makeUser" finished-at="2016-01-22T14:31:54Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MakeUserTest.validateNewUser()[pri:0, instance:backend.MakeUserTest@bfbefc] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MakeUserTest.validateNewUser()[pri:0, instance:backend.MakeUserTest@bfbefc] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:160)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:100)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateNewUser -->
      </class> <!-- backend.MakeUserTest -->
      <class name="frontend.FormVisibilityTest">
        <test-method status="SKIP" signature="openForm()[pri:0, instance:frontend.FormVisibilityTest@e64834]" name="openForm" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="open form" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openForm -->
        <test-method status="SKIP" signature="checkElementVisibility()[pri:0, instance:frontend.FormVisibilityTest@e64834]" name="checkElementVisibility" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="element visibility" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkElementVisibility -->
      </class> <!-- frontend.FormVisibilityTest -->
      <class name="frontend.FrontendLoginTest">
        <test-method status="SKIP" signature="frontendSetup()[pri:0, instance:frontend.FrontendLoginTest@8e7b84]" name="frontendSetup" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="wfp frontend setup" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendSetup -->
        <test-method status="SKIP" signature="frontendInvalidLogin()[pri:0, instance:frontend.FrontendLoginTest@8e7b84]" name="frontendInvalidLogin" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="wfp frontend invalid credentials login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendInvalidLogin -->
        <test-method status="SKIP" signature="frontendInvalidPassLogin()[pri:0, instance:frontend.FrontendLoginTest@8e7b84]" name="frontendInvalidPassLogin" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="wfp frontend invalid password login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendInvalidPassLogin -->
        <test-method status="SKIP" signature="frontendInvalidUserLogin()[pri:0, instance:frontend.FrontendLoginTest@8e7b84]" name="frontendInvalidUserLogin" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="wfp frontend invalid username login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendInvalidUserLogin -->
        <test-method status="SKIP" signature="frontendValidLogin()[pri:0, instance:frontend.FrontendLoginTest@8e7b84]" name="frontendValidLogin" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="5. wfp frontend valid login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendValidLogin -->
      </class> <!-- frontend.FrontendLoginTest -->
      <class name="backend.BackendLoginTest">
        <test-method status="PASS" signature="setupBeforeSuite(org.testng.ITestContext)[pri:0, instance:backend.BackendLoginTest@1d8867]" name="setupBeforeSuite" is-config="true" duration-ms="1146" started-at="2016-01-22T14:31:44Z" finished-at="2016-01-22T14:31:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@15e975c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeSuite -->
        <test-method status="FAIL" signature="setupBeforeSuite(org.testng.ITestContext)[pri:0, instance:frontend.FormVisibilityTest@e64834]" name="setupBeforeSuite" is-config="true" duration-ms="0" started-at="2016-01-22T14:31:45Z" finished-at="2016-01-22T14:31:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@15e975c]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to Workflow4people Forms] but found [Welkom bij Opleiding wijkverpleging]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to Workflow4people Forms] but found [Welkom bij Opleiding wijkverpleging]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at resources.FrontendLogin.submitForm(FrontendLogin.java:32)
	at resources.SuiteSetup.getFrontendDriver(SuiteSetup.java:43)
	at frontend.FormVisibilityTest.setupBeforeSuite(FormVisibilityTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:160)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:100)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeSuite -->
        <test-method status="SKIP" signature="setupBeforeSuite(org.testng.ITestContext)[pri:0, instance:backend.MakeUserTest@bfbefc]" name="setupBeforeSuite" is-config="true" duration-ms="0" started-at="2016-01-22T14:31:54Z" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeSuite -->
        <test-method status="SKIP" signature="setupBeforeSuite(org.testng.ITestContext)[pri:0, instance:frontend.FrontendLoginTest@8e7b84]" name="setupBeforeSuite" is-config="true" duration-ms="0" started-at="2016-01-22T14:31:54Z" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeSuite -->
        <test-method status="SKIP" signature="frontendSetup()[pri:0, instance:backend.BackendLoginTest@1d8867]" name="frontendSetup" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="wfp backend setup" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendSetup -->
        <test-method status="SKIP" signature="frontendInvalidUserLogin()[pri:0, instance:backend.BackendLoginTest@1d8867]" name="frontendInvalidUserLogin" duration-ms="1" started-at="2016-01-22T14:31:54Z" description="wfp frontend invalid username login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendInvalidUserLogin -->
        <test-method status="SKIP" signature="frontendInvalidPassLogin()[pri:0, instance:backend.BackendLoginTest@1d8867]" name="frontendInvalidPassLogin" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="wfp frontend invalid password login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendInvalidPassLogin -->
        <test-method status="SKIP" signature="frontendInvalidLogin()[pri:0, instance:backend.BackendLoginTest@1d8867]" name="frontendInvalidLogin" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="wfp frontend invalid credentials login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendInvalidLogin -->
        <test-method status="SKIP" signature="frontendValidLogin()[pri:0, instance:backend.BackendLoginTest@1d8867]" name="frontendValidLogin" duration-ms="0" started-at="2016-01-22T14:31:54Z" description="5. wfp frontend valid login" finished-at="2016-01-22T14:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- frontendValidLogin -->
        <test-method status="PASS" signature="setupAfterSuite()[pri:0, instance:backend.BackendLoginTest@1d8867]" name="setupAfterSuite" is-config="true" duration-ms="558" started-at="2016-01-22T14:31:54Z" finished-at="2016-01-22T14:31:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupAfterSuite -->
        <test-method status="FAIL" signature="setupAfterSuite()[pri:0, instance:frontend.FormVisibilityTest@e64834]" name="setupAfterSuite" is-config="true" duration-ms="0" started-at="2016-01-22T14:31:55Z" finished-at="2016-01-22T14:31:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at frontend.FormVisibilityTest.setupAfterSuite(FormVisibilityTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:160)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:100)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupAfterSuite -->
        <test-method status="FAIL" signature="setupAfterSuite()[pri:0, instance:frontend.FrontendLoginTest@8e7b84]" name="setupAfterSuite" is-config="true" duration-ms="0" started-at="2016-01-22T14:31:55Z" finished-at="2016-01-22T14:31:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at frontend.FrontendLoginTest.setupAfterSuite(FrontendLoginTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:160)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:100)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupAfterSuite -->
        <test-method status="FAIL" signature="setupAfterSuite()[pri:0, instance:backend.MakeUserTest@bfbefc]" name="setupAfterSuite" is-config="true" duration-ms="0" started-at="2016-01-22T14:31:55Z" finished-at="2016-01-22T14:31:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at backend.MakeUserTest.setupAfterSuite(MakeUserTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:160)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:100)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:188)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:166)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:101)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupAfterSuite -->
      </class> <!-- backend.BackendLoginTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
